### ISSUE TITLE
Images that are too large fail to load without any informative error message

### ISSUE THREAD

**Issue by andybak** [icosa-foundation/open-brush#688]
1. Give the user some actionable information
2. Check to see if our limits for the Quest still make sense.

**Comment by andybak** [comment]
Especially an issue with background images as people want to push the resolution for those nice and high. 6k seems to work. Not sure beyond that.

**Comment by eeropomell** [comment]
I'm looking to fix this currently.

(1): Regarding "Check to see if our limits for the Quest still make sense." are the limits the current memory usage of the game? ie just check if the image that the user wants to load won't crash the game?

(2): I just tried with a 200MB image and I'm getting different behavior on Quest and on PC in Unity. It seems like the bug is occurring only on PC for me?

With Quest (version: 2.7.0) I'm getting a black cross for the image icon, and I cannot even click on the image to load it:
![6ed305e8905f97c41fc2ddb61ae0abb4](https://github.com/icosa-foundation/open-brush/assets/97628152/9a3c6936-d588-4622-8814-85ac94cd8097)

On PC (version:  2.7.34), I'm getting a red question mark for the image, and I can load it (the question mark image placeholder) without any explicit errors (I guess this is what the issue is about?), except in Unity console I get the error: "Texture has out of range width / height"

Video showing the behavior: https://imgur.com/bdYdxs0

**Comment by eeropomell** [comment]
Thoughts on if the user sees something like this?

https://github.com/icosa-foundation/open-brush/assets/97628152/54eaac7e-39a9-4598-a2e6-b7b4fff135c0

This is a very quick implementation I made today, just want to get your thoughts on the visual side.

**Comment by andybak** [comment]
I'm not a huge fan of those floating disappearing notifications. Could it instead be part of the tooltip?

**Comment by eeropomell** [comment]
I agree. 

Below are some variations where the error message is in the tooltip, let me know what you think. I think I prefer the 4th one the most.

![e1425dfd5894c131ee9131fe9cc33be6](https://github.com/icosa-foundation/open-brush/assets/97628152/4b7965ad-3654-49b2-9a3c-a79d6085c8af)


![a55e09241a99ac48274a56453a752b52](https://github.com/icosa-foundation/open-brush/assets/97628152/691f499e-6ee7-4197-9c11-69c616fc1bb0)


![720f850874af93db61003de7e24d6cce](https://github.com/icosa-foundation/open-brush/assets/97628152/4253d00e-fc83-4e38-8027-473dba4049cb)



![3b17e4273b0bf13fcaa619ee2a9167a2](https://github.com/icosa-foundation/open-brush/assets/97628152/fe58d7f9-dfe1-41fa-99e0-1f8c6c3d2612)


![47f907ff591c829ab62f46faf134d8a5](https://github.com/icosa-foundation/open-brush/assets/97628152/623f24dd-ef4d-4c28-99ca-b40b2b722290)

**Comment by mikeskydev** [comment]
I personally like the first one, is that using the specific two line tooltip or is it the single line one stretched?
